name: Deploy documentation

on:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install Doxygen
        run: |
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_12_0/doxygen-1.12.0.linux.bin.tar.gz
          tar -xf doxygen-1.12.0.linux.bin.tar.gz
      - name: Generate docs
        run: ./doxygen-1.12.0/bin/doxygen
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'doc/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
